server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authenticationDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
<<<<<<< HEAD
    password: Root1234
=======
    password: pentiumd09
>>>>>>> 8e5b9713df90301e447f67f51f7442238b7e432d
  application:
    name: authentication-service

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    queue: user.queue
    exchange: user.exchange
    routingkey: user.routingkey
    host: localhost
    username: guest
    password: guest
    port: 15672