server:
  port: 8100
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/authdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect